// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/gatekeeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordUsageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Method           string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path             string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	OrganizationName string                 `protobuf:"bytes,3,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecordUsageRequest) Reset() {
	*x = RecordUsageRequest{}
	mi := &file_proto_gatekeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordUsageRequest) ProtoMessage() {}

func (x *RecordUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gatekeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordUsageRequest.ProtoReflect.Descriptor instead.
func (*RecordUsageRequest) Descriptor() ([]byte, []int) {
	return file_proto_gatekeeper_proto_rawDescGZIP(), []int{0}
}

func (x *RecordUsageRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RecordUsageRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RecordUsageRequest) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

type RecordUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cost          float64                `protobuf:"fixed64,1,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordUsageResponse) Reset() {
	*x = RecordUsageResponse{}
	mi := &file_proto_gatekeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordUsageResponse) ProtoMessage() {}

func (x *RecordUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gatekeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordUsageResponse.ProtoReflect.Descriptor instead.
func (*RecordUsageResponse) Descriptor() ([]byte, []int) {
	return file_proto_gatekeeper_proto_rawDescGZIP(), []int{1}
}

func (x *RecordUsageResponse) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type ValidateRequestRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrganizationName string                 `protobuf:"bytes,1,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	Method           string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path             string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ValidateRequestRequest) Reset() {
	*x = ValidateRequestRequest{}
	mi := &file_proto_gatekeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequestRequest) ProtoMessage() {}

func (x *ValidateRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gatekeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequestRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_gatekeeper_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateRequestRequest) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *ValidateRequestRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ValidateRequestRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ValidateRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *structpb.Struct       `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	Endpoint      *structpb.Struct       `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Subscription  *structpb.Struct       `protobuf:"bytes,3,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Remaining     int64                  `protobuf:"varint,4,opt,name=remaining,proto3" json:"remaining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequestResponse) Reset() {
	*x = ValidateRequestResponse{}
	mi := &file_proto_gatekeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequestResponse) ProtoMessage() {}

func (x *ValidateRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gatekeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequestResponse.ProtoReflect.Descriptor instead.
func (*ValidateRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_gatekeeper_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateRequestResponse) GetOrganization() *structpb.Struct {
	if x != nil {
		return x.Organization
	}
	return nil
}

func (x *ValidateRequestResponse) GetEndpoint() *structpb.Struct {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *ValidateRequestResponse) GetSubscription() *structpb.Struct {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *ValidateRequestResponse) GetRemaining() int64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

var File_proto_gatekeeper_proto protoreflect.FileDescriptor

const file_proto_gatekeeper_proto_rawDesc = "" +
	"\n" +
	"\x16proto/gatekeeper.proto\x12\n" +
	"gatekeeper\x1a\x1cgoogle/protobuf/struct.proto\"m\n" +
	"\x12RecordUsageRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12+\n" +
	"\x11organization_name\x18\x03 \x01(\tR\x10organizationName\")\n" +
	"\x13RecordUsageResponse\x12\x12\n" +
	"\x04cost\x18\x01 \x01(\x01R\x04cost\"q\n" +
	"\x16ValidateRequestRequest\x12+\n" +
	"\x11organization_name\x18\x01 \x01(\tR\x10organizationName\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"\xe6\x01\n" +
	"\x17ValidateRequestResponse\x12;\n" +
	"\forganization\x18\x01 \x01(\v2\x17.google.protobuf.StructR\forganization\x123\n" +
	"\bendpoint\x18\x02 \x01(\v2\x17.google.protobuf.StructR\bendpoint\x12;\n" +
	"\fsubscription\x18\x03 \x01(\v2\x17.google.protobuf.StructR\fsubscription\x12\x1c\n" +
	"\tremaining\x18\x04 \x01(\x03R\tremaining2\xbf\x01\n" +
	"\x11GatekeeperService\x12N\n" +
	"\vRecordUsage\x12\x1e.gatekeeper.RecordUsageRequest\x1a\x1f.gatekeeper.RecordUsageResponse\x12Z\n" +
	"\x0fValidateRequest\x12\".gatekeeper.ValidateRequestRequest\x1a#.gatekeeper.ValidateRequestResponseB7Z5github.com/bignyap/go-admin/internal/gatekeeper/protob\x06proto3"

var (
	file_proto_gatekeeper_proto_rawDescOnce sync.Once
	file_proto_gatekeeper_proto_rawDescData []byte
)

func file_proto_gatekeeper_proto_rawDescGZIP() []byte {
	file_proto_gatekeeper_proto_rawDescOnce.Do(func() {
		file_proto_gatekeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gatekeeper_proto_rawDesc), len(file_proto_gatekeeper_proto_rawDesc)))
	})
	return file_proto_gatekeeper_proto_rawDescData
}

var file_proto_gatekeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_gatekeeper_proto_goTypes = []any{
	(*RecordUsageRequest)(nil),      // 0: gatekeeper.RecordUsageRequest
	(*RecordUsageResponse)(nil),     // 1: gatekeeper.RecordUsageResponse
	(*ValidateRequestRequest)(nil),  // 2: gatekeeper.ValidateRequestRequest
	(*ValidateRequestResponse)(nil), // 3: gatekeeper.ValidateRequestResponse
	(*structpb.Struct)(nil),         // 4: google.protobuf.Struct
}
var file_proto_gatekeeper_proto_depIdxs = []int32{
	4, // 0: gatekeeper.ValidateRequestResponse.organization:type_name -> google.protobuf.Struct
	4, // 1: gatekeeper.ValidateRequestResponse.endpoint:type_name -> google.protobuf.Struct
	4, // 2: gatekeeper.ValidateRequestResponse.subscription:type_name -> google.protobuf.Struct
	0, // 3: gatekeeper.GatekeeperService.RecordUsage:input_type -> gatekeeper.RecordUsageRequest
	2, // 4: gatekeeper.GatekeeperService.ValidateRequest:input_type -> gatekeeper.ValidateRequestRequest
	1, // 5: gatekeeper.GatekeeperService.RecordUsage:output_type -> gatekeeper.RecordUsageResponse
	3, // 6: gatekeeper.GatekeeperService.ValidateRequest:output_type -> gatekeeper.ValidateRequestResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_gatekeeper_proto_init() }
func file_proto_gatekeeper_proto_init() {
	if File_proto_gatekeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gatekeeper_proto_rawDesc), len(file_proto_gatekeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gatekeeper_proto_goTypes,
		DependencyIndexes: file_proto_gatekeeper_proto_depIdxs,
		MessageInfos:      file_proto_gatekeeper_proto_msgTypes,
	}.Build()
	File_proto_gatekeeper_proto = out.File
	file_proto_gatekeeper_proto_goTypes = nil
	file_proto_gatekeeper_proto_depIdxs = nil
}
