services:
  go-admin:
    container_name: go-admin
    image: go-admin:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     CACHE_BUST: ${CACHE_BUST}
    #     BINARY_NAME: "go-admin"
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      ENVIRONMENT: "dev"
      REDIS_ADDR: ${REDIS_ADDR}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      PUBSUB_ENABLED: ${PUBSUB_ENABLED}
      PUBSUB_TYPE: ${PUBSUB_TYPE}
      PUBSUB_NAMESPACE: ${PUBSUB_NAMESPACE}
      SERVER_TYPE: ${SERVER_TYPE}
    ports:
      - '8081:8080'
    expose:
      - '8081'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1;"]
      interval: 19s
      timeout: 5s
      retries: 10
    depends_on:
      postgres:
        condition: service_healthy
      # gatari-db-init:
      #   condition: service_completed_successfully

  gate-keeper:
    container_name: gate-keeper
    image: gate-keeper:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     CACHE_BUST: ${CACHE_BUST}
    #     BINARY_NAME: "gate-keeper"
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      REDIS_ADDR: ${REDIS_ADDR}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      ENVIRONMENT: "dev"
      PUBSUB_ENABLED: ${PUBSUB_ENABLED}
      PUBSUB_TYPE: ${PUBSUB_TYPE}
      PUBSUB_NAMESPACE: ${PUBSUB_NAMESPACE}
      GATEKEEPER_MODE: ${GATEKEEPER_MODE}
      PROXY_TARGET: ${PROXY_TARGET}
      SERVER_TYPE: ${SERVER_TYPE}
    ports:
      - '8082:8080'
    expose:
      - '8082'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1;"]
      interval: 19s
      timeout: 5s
      retries: 10
    depends_on:
      postgres:
        condition: service_healthy
      # gatari-db-init:
      #   condition: service_completed_successfully

  # gatari-db-init:
  #   container_name: gatari-db-init
  #   image: bignya/gatari-db-init:latest
  #   environment:
  #     DB_DSN: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  gatari-mcp-server:
    container_name: gatari-mcp-server
    image: gatari-mcp-server:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     CACHE_BUST: ${CACHE_BUST}
    restart: always
    environment:
      BASE_URL: ${BASE_URL}
      PORT: ${PORT}
      OPENAPI_SPEC_PATH: ${OPENAPI_SPEC_PATH}
    ports:
      - '8084:8084'
    expose:
      - '8084'
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:8084/mcp/status || exit 1;"]
    #   interval: 19s
    #   timeout: 5s
    #   retries: 10
    # depends_on:
    #   go-admin:
    #     condition: service_healthy

  gatari-mcp-client:
    container_name: gatari-mcp-client
    image: gatari-mcp-client:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     CACHE_BUST: ${CACHE_BUST}
    restart: always
    environment:
      MCP_SERVER_URL: ${BASE_URL}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      PORT: ${PORT}
      LLM_PROVIDER: ${LLM_PROVIDER}
      OPENAI_MODEL: ${OPENAI_MODEL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_MODEL: ${GEMINI_MODEL}
    ports:
      - '9000:9000'
    expose:
      - '9000'
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:9000/health || exit 1;"]
    #   interval: 19s
    #   timeout: 5s
    #   retries: 10
    # depends_on:
    #   gatari-mcp-server:
    #     condition: service_healthy

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - go-admin-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - go-admin-redis-data:/data
    ports:
      - '6379:6379'
    expose:
      - '6379'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 10

  gatari-apidoc:
    image: styled-swagger-ui:latest
    restart: always
    ports:
      - '8083:80'
    expose:
      - '8083'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./apidoc:/usr/share/nginx/html/apidoc
      - ./apidoc/config.js:/usr/share/nginx/html/config.js

volumes:
  go-admin-postgres-data:
    driver: local
  go-admin-redis-data:
    driver: local