// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: endpoints.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteApiEndpointById = `-- name: DeleteApiEndpointById :exec
DELETE FROM api_endpoint
WHERE api_endpoint_id = $1
`

func (q *Queries) DeleteApiEndpointById(ctx context.Context, apiEndpointID int32) error {
	_, err := q.db.Exec(ctx, deleteApiEndpointById, apiEndpointID)
	return err
}

const listApiEndpoint = `-- name: ListApiEndpoint :many
SELECT api_endpoint_id, endpoint_name, endpoint_description FROM api_endpoint
ORDER BY endpoint_name
LIMIT $1 OFFSET $2
`

type ListApiEndpointParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListApiEndpoint(ctx context.Context, arg ListApiEndpointParams) ([]ApiEndpoint, error) {
	rows, err := q.db.Query(ctx, listApiEndpoint, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiEndpoint{}
	for rows.Next() {
		var i ApiEndpoint
		if err := rows.Scan(&i.ApiEndpointID, &i.EndpointName, &i.EndpointDescription); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerApiEndpoint = `-- name: RegisterApiEndpoint :one
INSERT INTO api_endpoint (endpoint_name, endpoint_description) 
VALUES ($1, $2)
RETURNING api_endpoint_id
`

type RegisterApiEndpointParams struct {
	EndpointName        string
	EndpointDescription pgtype.Text
}

func (q *Queries) RegisterApiEndpoint(ctx context.Context, arg RegisterApiEndpointParams) (int32, error) {
	row := q.db.QueryRow(ctx, registerApiEndpoint, arg.EndpointName, arg.EndpointDescription)
	var api_endpoint_id int32
	err := row.Scan(&api_endpoint_id)
	return api_endpoint_id, err
}

type RegisterApiEndpointsParams struct {
	EndpointName        string
	EndpointDescription pgtype.Text
}
