// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiEndpoint struct {
	ApiEndpointID       int32
	EndpointName        string
	EndpointDescription pgtype.Text
	HttpMethod          string
	PathTemplate        string
	ResourceTypeID      int32
}

type ApiUsageSummary struct {
	UsageSummaryID int32
	UsageStartDate int32
	UsageEndDate   int32
	TotalCalls     int32
	TotalCost      float64
	SubscriptionID int32
	ApiEndpointID  int32
	OrganizationID int32
}

type BillingHistory struct {
	BillingID        int32
	BillingStartDate int32
	BillingEndDate   int32
	TotalAmountDue   float64
	TotalCalls       int32
	PaymentStatus    string
	PaymentDate      pgtype.Int4
	BillingCreatedAt int32
	SubscriptionID   int32
}

type CustomEndpointPricing struct {
	CustomEndpointPricingID int32
	CustomCostPerCall       float64
	CustomRateLimit         int32
	SubscriptionID          int32
	TierBasePricingID       int32
}

type Organization struct {
	OrganizationID           int32
	OrganizationName         string
	OrganizationCreatedAt    int32
	OrganizationUpdatedAt    int32
	OrganizationRealm        string
	OrganizationCountry      pgtype.Text
	OrganizationSupportEmail string
	OrganizationActive       pgtype.Bool
	OrganizationReportQ      pgtype.Bool
	OrganizationConfig       pgtype.Text
	OrganizationTypeID       int32
}

type OrganizationPermission struct {
	OrganizationPermissionID int32
	ResourceTypeID           int32
	PermissionCode           string
	OrganizationID           int32
}

type OrganizationType struct {
	OrganizationTypeID   int32
	OrganizationTypeName string
}

type ResourceType struct {
	ResourceTypeID          int32
	ResourceTypeCode        string
	ResourceTypeName        string
	ResourceTypeDescription pgtype.Text
}

type Subscription struct {
	SubscriptionID          int32
	SubscriptionName        string
	SubscriptionType        string
	SubscriptionCreatedDate int32
	SubscriptionUpdatedDate int32
	SubscriptionStartDate   int32
	SubscriptionApiLimit    pgtype.Int4
	SubscriptionExpiryDate  pgtype.Int4
	SubscriptionDescription pgtype.Text
	SubscriptionStatus      pgtype.Bool
	OrganizationID          int32
	SubscriptionTierID      int32
}

type SubscriptionTier struct {
	SubscriptionTierID int32
	TierName           string
	TierArchived       bool
	TierDescription    pgtype.Text
	TierCreatedAt      int32
	TierUpdatedAt      int32
}

type TierBasePricing struct {
	TierBasePricingID  int32
	BaseCostPerCall    float64
	BaseRateLimit      pgtype.Int4
	ApiEndpointID      int32
	SubscriptionTierID int32
}
